DROP TABLE MONTH_TRANSACTION_TBL;
DROP TABLE MONTH_TBL;
DROP TABLE CATEGORY_TBL;
DROP SEQUENCE MONTH_ID_SEQ;
DROP SEQUENCE CATEGORY_ID_SEQ;
DROP SEQUENCE MONTH_TRANSACTION_ID_SEQ;

CREATE SEQUENCE MONTH_ID_SEQ  
  MINVALUE 0 
  MAXVALUE 99999999999999 
  INCREMENT BY 1 
  START WITH 0;

CREATE SEQUENCE CATEGORY_ID_SEQ  
  MINVALUE 0 
  MAXVALUE 99999999999999 
  INCREMENT BY 1 
  START WITH 0;

CREATE SEQUENCE MONTH_TRANSACTION_ID_SEQ  
  MINVALUE 0 
  MAXVALUE 99999999999999 
  INCREMENT BY 1 
  START WITH 0;

CREATE TABLE MONTH_TBL (
  ID NUMBER,
  NAME VARCHAR2(15),
  CONSTRAINT MONTH_PK PRIMARY KEY (ID)
  );

CREATE TABLE CATEGORY_TBL (
  ID NUMBER,
  NAME VARCHAR2(20),
  CONSTRAINT CATEGORY_PK PRIMARY KEY (ID)
  );

CREATE TABLE MONTH_TRANSACTION_TBL (
  ID NUMBER,
  MONTH_ID NUMBER,
  NAME VARCHAR(30),
  AMOUNT NUMBER,
  TYPE VARCHAR2(20),
  CATEGORY_ID NUMBER,
  CONSTRAINT MONTH_TRANSACTION_PK PRIMARY KEY (ID),
  CONSTRAINT MONTH_TRANSACTION_MONTH_FK FOREIGN KEY (MONTH_ID) REFERENCES MONTH_TBL,
  CONSTRAINT MONTH_TRANSACTION_CATEGORY_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY_TBL
  );
  
INSERT INTO MONTH_TBL VALUES(MONTH_ID_SEQ.NEXTVAL, 'January 2016'); 
INSERT INTO MONTH_TBL VALUES(MONTH_ID_SEQ.NEXTVAL, 'February 2016'); 
INSERT INTO MONTH_TBL VALUES(MONTH_ID_SEQ.NEXTVAL, 'March 2016'); 
INSERT INTO MONTH_TBL VALUES(MONTH_ID_SEQ.NEXTVAL, 'April 2016'); 
INSERT INTO MONTH_TBL VALUES(MONTH_ID_SEQ.NEXTVAL, 'May 2016'); 
INSERT INTO MONTH_TBL VALUES(MONTH_ID_SEQ.NEXTVAL, 'June 2016'); 

INSERT INTO CATEGORY_TBL VALUES(CATEGORY_ID_SEQ.NEXTVAL, 'salary');
INSERT INTO CATEGORY_TBL VALUES(CATEGORY_ID_SEQ.NEXTVAL, 'accommodation');
INSERT INTO CATEGORY_TBL VALUES(CATEGORY_ID_SEQ.NEXTVAL, 'transportation');
INSERT INTO CATEGORY_TBL VALUES(CATEGORY_ID_SEQ.NEXTVAL, 'food');

INSERT INTO MONTH_TRANSACTION_TBL VALUES(MONTH_TRANSACTION_ID_SEQ.NEXTVAL, 1, 'accommodation', 7000, 'expense',2); 
INSERT INTO MONTH_TRANSACTION_TBL VALUES(MONTH_TRANSACTION_ID_SEQ.NEXTVAL, 1, 'gas for car', 2000, 'expense', 2); 
INSERT INTO MONTH_TRANSACTION_TBL VALUES(MONTH_TRANSACTION_ID_SEQ.NEXTVAL, 1, 'apples', 1200, 'expense', 4); 
INSERT INTO MONTH_TRANSACTION_TBL VALUES(MONTH_TRANSACTION_ID_SEQ.NEXTVAL, 1, 'salaryJan', 21738, 'income', 1); 
INSERT INTO MONTH_TRANSACTION_TBL VALUES(MONTH_TRANSACTION_ID_SEQ.NEXTVAL, 2, 'salaryFeb', 28214, 'income', 1);
INSERT INTO MONTH_TRANSACTION_TBL VALUES(MONTH_TRANSACTION_ID_SEQ.NEXTVAL, 3, 'salaryMar', 25108, 'income',1);
INSERT INTO MONTH_TRANSACTION_TBL VALUES(MONTH_TRANSACTION_ID_SEQ.NEXTVAL, 4, 'salary', 20136, 'income', 1);
INSERT INTO MONTH_TRANSACTION_TBL VALUES(MONTH_TRANSACTION_ID_SEQ.NEXTVAL, 5, 'salary', 27444, 'income', 1);
INSERT INTO MONTH_TRANSACTION_TBL VALUES(MONTH_TRANSACTION_ID_SEQ.NEXTVAL, 6, 'salary', 22890, 'income', 1);

COMMIT;
