DROP TABLE EXPENSE;
DROP TABLE INCOME;
DROP TABLE MONTH;

CREATE TABLE MONTH (
  ID NUMBER,
  NAME VARCHAR2(15),
  CONSTRAINT MONTH_PK PRIMARY KEY (ID)
  );

CREATE TABLE EXPENSE (
  ID NUMBER,
  MONTH_ID NUMBER,
  EXPENSE_NAME VARCHAR(30),
  EXPENSE_AMOUNT NUMBER,
  CONSTRAINT EXPENSE_PK PRIMARY KEY (ID),
  CONSTRAINT EXPENSE_FK FOREIGN KEY (MONTH_ID) REFERENCES MONTH
  ); 
  
  
CREATE TABLE INCOME (
  ID NUMBER,
  MONTH_ID NUMBER,
  INCOME_NAME VARCHAR(20),
  INCOME_AMOUNT NUMBER,
  CONSTRAINT INCOME_PK PRIMARY KEY (ID),
  CONSTRAINT INCOME_FK FOREIGN KEY (MONTH_ID) REFERENCES MONTH
  );
  
INSERT INTO MONTH VALUES(1, 'January 2016'); 
INSERT INTO MONTH VALUES(2, 'February 2016'); 
INSERT INTO MONTH VALUES(3, 'March 2016'); 
INSERT INTO MONTH VALUES(4, 'April 2016'); 
INSERT INTO MONTH VALUES(5, 'May 2016'); 
INSERT INTO MONTH VALUES(6, 'June 2016'); 

INSERT INTO EXPENSE VALUES(1, 1, 'accommodation', 7000); 
INSERT INTO EXPENSE VALUES(2, 1, 'transportation', 2000); 
INSERT INTO EXPENSE VALUES(3, 1, 'food', 1200); 

INSERT INTO INCOME VALUES(1, 1, 'salary', 21738); 
INSERT INTO INCOME VALUES(2, 2, 'salary', 28214);
INSERT INTO INCOME VALUES(3, 3, 'salary', 25108);
INSERT INTO INCOME VALUES(4, 4, 'salary', 20136);
INSERT INTO INCOME VALUES(5, 5, 'salary', 27444);
INSERT INTO INCOME VALUES(6, 6, 'salary', 22890);

COMMIT;
