package view;

import controller.Controller;
import entity.Category;
import entity.Month;
import entity.MonthTransaction;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.AbstractTableModel;

public class ExpensesCalculator extends javax.swing.JFrame {

    /**
     * Creates new form ExpensesCalculator
     */
    private Controller controller;

    public ExpensesCalculator() {
        controller = new Controller();
        initComponents();
        initMonths();
        initCategories();
        initTypes();
        fillMonthTable( controller.getMonthTransactions() );
        this.setLocationRelativeTo( null );
        jLayeredPaneViewTransactions.setVisible( false );
        jLayeredPaneAddTransaction.setVisible( false );
    }

    private void initMonths() {
        List<Month> allMonths = controller.getMonths();
        String[] months = new String[ allMonths.size() + 1 ];
        months[ 0 ] = "-ALL-";
        for ( int i = 1; i < allMonths.size() + 1; i++ ) {
            months[ i ] = allMonths.get( i - 1 ).getName();
        }

        String[] monthsForAddTransactionFrame = Arrays.copyOfRange( months, 1, months.length );

        jComboBoxMonths.setModel( new javax.swing.DefaultComboBoxModel( months ) );
        jComboBoxMonthsAddTransaction.setModel( new javax.swing.DefaultComboBoxModel( monthsForAddTransactionFrame ) );
    }

    private void initCategories() {
        List<Category> allCategories = controller.getCategories();
        String[] categories = new String[ allCategories.size() + 1 ];
        categories[ 0 ] = "-ALL-";
        for ( int i = 1; i < allCategories.size() + 1; i++ ) {
            categories[ i ] = allCategories.get( i - 1 ).getName();
        }
        String[] categoriesForAddTransactionFrame = Arrays.copyOfRange( categories, 1, categories.length );

        jComboBoxCategory.setModel( new javax.swing.DefaultComboBoxModel( categories ) );
        jComboBoxCategoryAddTransaction.setModel( new javax.swing.DefaultComboBoxModel( categoriesForAddTransactionFrame ) );
    }

    private void initTypes() {

        String[] types = new String[ 3 ];

        types[ 0 ] = "-ALL-";
        types[ 1 ] = "income";
        types[ 2 ] = "expense";

        jComboBoType.setModel( new javax.swing.DefaultComboBoxModel( types ) );
    }

    class CustomModel extends AbstractTableModel {

        private Object[][] result;
        private String[] columnNames;

        public CustomModel( Object[][] result, String[] columnNames ) {
            this.result = result;
            this.columnNames = columnNames;
        }

        @Override
        public int getRowCount() {
            return result.length;
        }

        @Override
        public int getColumnCount() {
            return columnNames.length;
        }

        @Override
        public String getColumnName( int col ) {
            return columnNames[ col ];
        }

        @Override
        public Object getValueAt( int i, int i1 ) {
            return result[ i ][ i1 ];
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPaneViewTransactions = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxMonths = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxCategory = new javax.swing.JComboBox();
        jComboBoType = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMonthTransactions = new javax.swing.JTable();
        jLayeredPaneAddTransaction = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldTransactionName = new javax.swing.JTextField();
        jComboBoxTypeAddTransaction = new javax.swing.JComboBox();
        jComboBoxMonthsAddTransaction = new javax.swing.JComboBox();
        jComboBoxCategoryAddTransaction = new javax.swing.JComboBox();
        jTextFieldAmount = new javax.swing.JTextField();
        jButtonAddTransaction = new javax.swing.JButton();
        jLabelInsertTransactionStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemViewTransactions = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 385));

        jLayeredPaneViewTransactions.setPreferredSize(new java.awt.Dimension(540, 360));

        jLabel1.setText("Month/Year");

        jComboBoxMonths.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month1", "Month2", "Month3" }));
        jComboBoxMonths.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMonthsItemStateChanged(evt);
            }
        });
        jComboBoxMonths.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBoxMonthsMouseReleased(evt);
            }
        });
        jComboBoxMonths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMonthsActionPerformed(evt);
            }
        });
        jComboBoxMonths.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxMonthsPropertyChange(evt);
            }
        });

        jLabel2.setText("Transaction Category");

        jComboBoxCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Food", "Drinks", "Soviet" }));
        jComboBoxCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoryActionPerformed(evt);
            }
        });

        jComboBoType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoTypeActionPerformed(evt);
            }
        });

        jLabel3.setText("Transaction Type");

        jTableMonthTransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Type", "Month", "Category", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMonthTransactions);
        if (jTableMonthTransactions.getColumnModel().getColumnCount() > 0) {
            jTableMonthTransactions.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jLayeredPaneViewTransactionsLayout = new javax.swing.GroupLayout(jLayeredPaneViewTransactions);
        jLayeredPaneViewTransactions.setLayout(jLayeredPaneViewTransactionsLayout);
        jLayeredPaneViewTransactionsLayout.setHorizontalGroup(
            jLayeredPaneViewTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneViewTransactionsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jLayeredPaneViewTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPaneViewTransactionsLayout.createSequentialGroup()
                        .addGroup(jLayeredPaneViewTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jComboBoxMonths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jLayeredPaneViewTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPaneViewTransactionsLayout.createSequentialGroup()
                                .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136)
                                .addComponent(jComboBoType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPaneViewTransactionsLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(77, 77, 77)
                                .addComponent(jLabel3)))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jLayeredPaneViewTransactionsLayout.setVerticalGroup(
            jLayeredPaneViewTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneViewTransactionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneViewTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(jLayeredPaneViewTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPaneViewTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxMonths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jLayeredPaneViewTransactions.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneViewTransactions.setLayer(jComboBoxMonths, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneViewTransactions.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneViewTransactions.setLayer(jComboBoxCategory, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneViewTransactions.setLayer(jComboBoType, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneViewTransactions.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneViewTransactions.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setText("Name");

        jLabel5.setText("Type");

        jLabel6.setText("Month");

        jLabel7.setText("Category");

        jLabel8.setText("Amount");

        jTextFieldTransactionName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTransactionNameActionPerformed(evt);
            }
        });

        jComboBoxTypeAddTransaction.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "income", "expense" }));
        jComboBoxTypeAddTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypeAddTransactionActionPerformed(evt);
            }
        });

        jComboBoxMonthsAddTransaction.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxCategoryAddTransaction.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAmountActionPerformed(evt);
            }
        });

        jButtonAddTransaction.setText("Add");
        jButtonAddTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTransactionActionPerformed(evt);
            }
        });

        jLabelInsertTransactionStatus.setText("Status :");

        javax.swing.GroupLayout jLayeredPaneAddTransactionLayout = new javax.swing.GroupLayout(jLayeredPaneAddTransaction);
        jLayeredPaneAddTransaction.setLayout(jLayeredPaneAddTransactionLayout);
        jLayeredPaneAddTransactionLayout.setHorizontalGroup(
            jLayeredPaneAddTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneAddTransactionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jLayeredPaneAddTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPaneAddTransactionLayout.createSequentialGroup()
                        .addComponent(jButtonAddTransaction)
                        .addGap(28, 28, 28)
                        .addComponent(jLabelInsertTransactionStatus))
                    .addGroup(jLayeredPaneAddTransactionLayout.createSequentialGroup()
                        .addGroup(jLayeredPaneAddTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(116, 116, 116)
                        .addGroup(jLayeredPaneAddTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxMonthsAddTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTypeAddTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCategoryAddTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPaneAddTransactionLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(134, 134, 134)
                        .addComponent(jTextFieldTransactionName, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPaneAddTransactionLayout.setVerticalGroup(
            jLayeredPaneAddTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneAddTransactionLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jLayeredPaneAddTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTransactionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneAddTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxTypeAddTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneAddTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxMonthsAddTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jLayeredPaneAddTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxCategoryAddTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jLayeredPaneAddTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jLayeredPaneAddTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddTransaction)
                    .addComponent(jLabelInsertTransactionStatus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPaneAddTransaction.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAddTransaction.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAddTransaction.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAddTransaction.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAddTransaction.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAddTransaction.setLayer(jTextFieldTransactionName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAddTransaction.setLayer(jComboBoxTypeAddTransaction, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAddTransaction.setLayer(jComboBoxMonthsAddTransaction, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAddTransaction.setLayer(jComboBoxCategoryAddTransaction, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAddTransaction.setLayer(jTextFieldAmount, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAddTransaction.setLayer(jButtonAddTransaction, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAddTransaction.setLayer(jLabelInsertTransactionStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(228, 25));

        jMenu1.setText("Transactions");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItemViewTransactions.setText("View");
        jMenuItemViewTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewTransactionsActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemViewTransactions);

        jMenuItem1.setText("Add");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Something else");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPaneViewTransactions, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(jLayeredPaneAddTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPaneViewTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPaneAddTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxMonthsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxMonthsMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMonthsMouseReleased

    private void jComboBoxMonthsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMonthsItemStateChanged

    }//GEN-LAST:event_jComboBoxMonthsItemStateChanged

    private void jComboBoxMonthsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxMonthsPropertyChange

    }//GEN-LAST:event_jComboBoxMonthsPropertyChange

    private void jComboBoxMonthsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMonthsActionPerformed
        System.out.println( "Month Clicked : " + jComboBoxMonths.getSelectedItem() );
        String monthName = "" + jComboBoxMonths.getSelectedItem();
        String selectedMonth = jComboBoxMonths.getSelectedItem().toString();
        List<MonthTransaction> monthTransactions;
        if ( "-ALL-".equals( selectedMonth ) ) {
            monthTransactions = controller.getMonthTransactions();
        } else {
            monthTransactions = controller.getTransactionsByMonth( monthName );
        }

        fillMonthTable( monthTransactions );
    }//GEN-LAST:event_jComboBoxMonthsActionPerformed

    private void jComboBoxCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoryActionPerformed
        System.out.println( "Category Clicked : " + jComboBoxCategory.getSelectedItem().toString() );

        String categoryName = jComboBoxCategory.getSelectedItem().toString();
        //String selectedCategory = jComboBoxMonths.getSelectedItem().toString();
        List<MonthTransaction> monthTransactions;
        if ( "-ALL-".equals( categoryName ) ) {
            monthTransactions = controller.getMonthTransactions();
        } else {
            monthTransactions = controller.getTransactionsByCategory( categoryName );
        }

        fillMonthTable( monthTransactions );
    }//GEN-LAST:event_jComboBoxCategoryActionPerformed

    private void jComboBoTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoTypeActionPerformed
        System.out.println( "Type Clicked : " + jComboBoType.getSelectedItem() );

        String type = jComboBoType.getSelectedItem().toString();
        //String selectedCategory = jComboBoxMonths.getSelectedItem().toString();
        List<MonthTransaction> monthTransactions;
        if ( "-ALL-".equals( type ) ) {
            monthTransactions = controller.getMonthTransactions();
        } else {
            monthTransactions = controller.getTransactionsByType( type );
        }

        fillMonthTable( monthTransactions );
    }//GEN-LAST:event_jComboBoTypeActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jTextFieldTransactionNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTransactionNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTransactionNameActionPerformed

    private void jComboBoxTypeAddTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeAddTransactionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTypeAddTransactionActionPerformed

    private void jTextFieldAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAmountActionPerformed

    private void jMenuItemViewTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewTransactionsActionPerformed
        jLayeredPaneViewTransactions.setVisible( true );
        jLayeredPaneAddTransaction.setVisible( false );
    }//GEN-LAST:event_jMenuItemViewTransactionsActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jLayeredPaneViewTransactions.setVisible( false );
        jLayeredPaneAddTransaction.setVisible( true );
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButtonAddTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTransactionActionPerformed
        boolean status = controller.
                addMonthTransactions( jTextFieldTransactionName.getText(),
                                      jComboBoxMonthsAddTransaction.getSelectedItem().toString(),
                                      jComboBoxCategoryAddTransaction.getSelectedItem().toString(),
                                      jComboBoxTypeAddTransaction.getSelectedItem().toString(),
                                      Double.parseDouble( jTextFieldAmount.getText() ) );
        jLabelInsertTransactionStatus.setText(
                status
                        ? "Month Transaction was inserted successfully!"
                        : "Internal error while inserting month transaction"
        );
    }//GEN-LAST:event_jButtonAddTransactionActionPerformed

    private void fillMonthTable( List<MonthTransaction> monthTransactions ) {
        Object[][] twoDimensionalArrayForTables = new Object[ monthTransactions.size() ][ 5 ];
        for ( int i = 0; i < monthTransactions.size(); i++ ) {
            twoDimensionalArrayForTables[ i ][ 0 ] = monthTransactions.get( i ).getName();
            twoDimensionalArrayForTables[ i ][ 1 ] = monthTransactions.get( i ).getType();
            twoDimensionalArrayForTables[ i ][ 2 ] = monthTransactions.get( i ).getMonthId();
            twoDimensionalArrayForTables[ i ][ 3 ] = monthTransactions.get( i ).getCategoryId();
            twoDimensionalArrayForTables[ i ][ 4 ] = monthTransactions.get( i ).getAmount();
        }

        String[] rowNames = new String[]{ "Name", "Type", "Month", "Category", "Amount" };
        jTableMonthTransactions.setModel( new CustomModel( twoDimensionalArrayForTables, rowNames ) );
        jTableMonthTransactions.getTableHeader().setReorderingAllowed( false );
    }

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ) {
                if ( "Nimbus".equals( info.getName() ) ) {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        } catch ( ClassNotFoundException ex ) {
            java.util.logging.Logger.getLogger( ExpensesCalculator.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( InstantiationException ex ) {
            java.util.logging.Logger.getLogger( ExpensesCalculator.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( IllegalAccessException ex ) {
            java.util.logging.Logger.getLogger( ExpensesCalculator.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( javax.swing.UnsupportedLookAndFeelException ex ) {
            java.util.logging.Logger.getLogger( ExpensesCalculator.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable() {
            public void run() {
                new ExpensesCalculator().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddTransaction;
    private javax.swing.JComboBox jComboBoType;
    private javax.swing.JComboBox jComboBoxCategory;
    private javax.swing.JComboBox jComboBoxCategoryAddTransaction;
    private javax.swing.JComboBox jComboBoxMonths;
    private javax.swing.JComboBox jComboBoxMonthsAddTransaction;
    private javax.swing.JComboBox jComboBoxTypeAddTransaction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelInsertTransactionStatus;
    private javax.swing.JLayeredPane jLayeredPaneAddTransaction;
    private javax.swing.JLayeredPane jLayeredPaneViewTransactions;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemViewTransactions;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMonthTransactions;
    private javax.swing.JTextField jTextFieldAmount;
    private javax.swing.JTextField jTextFieldTransactionName;
    // End of variables declaration//GEN-END:variables
}
